import '../globals.css'
import { Inter } from 'next/font/google'
import Providers from '../provider'
import {redirect} from 'next/navigation'
import { getServerSession } from 'next-auth'
import { authOptions } from '../api/auth/[...nextauth]/route'
import HeaderBar from './headerBar'
import ToastBox from '@/components/Toast'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children, 
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions);

  if (!session) {
    return redirect("/login")
  }

  return (
    <html lang="en">
      <body className={`${inter.className} from-slate-950 to-sky-950 bg-gradient-to-tr w-screen h-screen`}>
        <Providers session={session}>
          <HeaderBar />
          <div className="h-screen w-screen pt-20">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  )
}
