import '../../globals.css'
import { Inter } from 'next/font/google'
import Providers from '../../provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children, 
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className + " bg-slate-900"}>
        <Providers session={null}>
          {children}
        </Providers>
      </body>
    </html>
  )
}
