/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface CheckerInterface extends ethers.utils.Interface {
  functions: {
    "USD()": FunctionFragment;
    "checkPrice(address)": FunctionFragment;
    "getBalancePrices(address,address[])": FunctionFragment;
    "getBalances(address,address[])": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "USD", values?: undefined): string;
  encodeFunctionData(functionFragment: "checkPrice", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getBalancePrices",
    values: [string, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getBalances",
    values: [string, string[]]
  ): string;

  decodeFunctionResult(functionFragment: "USD", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "checkPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBalancePrices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBalances",
    data: BytesLike
  ): Result;

  events: {};
}

export class Checker extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: CheckerInterface;

  functions: {
    USD(overrides?: CallOverrides): Promise<[string]>;

    "USD()"(overrides?: CallOverrides): Promise<[string]>;

    checkPrice(token: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    "checkPrice(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getBalancePrices(
      user: string,
      coins: string[],
      overrides?: CallOverrides
    ): Promise<
      [
        ([string, BigNumber, BigNumber, boolean] & {
          addr: string;
          balance: BigNumber;
          price: BigNumber;
          error: boolean;
        })[]
      ]
    >;

    "getBalancePrices(address,address[])"(
      user: string,
      coins: string[],
      overrides?: CallOverrides
    ): Promise<
      [
        ([string, BigNumber, BigNumber, boolean] & {
          addr: string;
          balance: BigNumber;
          price: BigNumber;
          error: boolean;
        })[]
      ]
    >;

    getBalances(
      user: string,
      coins: string[],
      overrides?: CallOverrides
    ): Promise<
      [
        ([string, BigNumber, boolean] & {
          addr: string;
          balance: BigNumber;
          error: boolean;
        })[]
      ]
    >;

    "getBalances(address,address[])"(
      user: string,
      coins: string[],
      overrides?: CallOverrides
    ): Promise<
      [
        ([string, BigNumber, boolean] & {
          addr: string;
          balance: BigNumber;
          error: boolean;
        })[]
      ]
    >;
  };

  USD(overrides?: CallOverrides): Promise<string>;

  "USD()"(overrides?: CallOverrides): Promise<string>;

  checkPrice(token: string, overrides?: CallOverrides): Promise<BigNumber>;

  "checkPrice(address)"(
    token: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getBalancePrices(
    user: string,
    coins: string[],
    overrides?: CallOverrides
  ): Promise<
    ([string, BigNumber, BigNumber, boolean] & {
      addr: string;
      balance: BigNumber;
      price: BigNumber;
      error: boolean;
    })[]
  >;

  "getBalancePrices(address,address[])"(
    user: string,
    coins: string[],
    overrides?: CallOverrides
  ): Promise<
    ([string, BigNumber, BigNumber, boolean] & {
      addr: string;
      balance: BigNumber;
      price: BigNumber;
      error: boolean;
    })[]
  >;

  getBalances(
    user: string,
    coins: string[],
    overrides?: CallOverrides
  ): Promise<
    ([string, BigNumber, boolean] & {
      addr: string;
      balance: BigNumber;
      error: boolean;
    })[]
  >;

  "getBalances(address,address[])"(
    user: string,
    coins: string[],
    overrides?: CallOverrides
  ): Promise<
    ([string, BigNumber, boolean] & {
      addr: string;
      balance: BigNumber;
      error: boolean;
    })[]
  >;

  callStatic: {
    USD(overrides?: CallOverrides): Promise<string>;

    "USD()"(overrides?: CallOverrides): Promise<string>;

    checkPrice(token: string, overrides?: CallOverrides): Promise<BigNumber>;

    "checkPrice(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBalancePrices(
      user: string,
      coins: string[],
      overrides?: CallOverrides
    ): Promise<
      ([string, BigNumber, BigNumber, boolean] & {
        addr: string;
        balance: BigNumber;
        price: BigNumber;
        error: boolean;
      })[]
    >;

    "getBalancePrices(address,address[])"(
      user: string,
      coins: string[],
      overrides?: CallOverrides
    ): Promise<
      ([string, BigNumber, BigNumber, boolean] & {
        addr: string;
        balance: BigNumber;
        price: BigNumber;
        error: boolean;
      })[]
    >;

    getBalances(
      user: string,
      coins: string[],
      overrides?: CallOverrides
    ): Promise<
      ([string, BigNumber, boolean] & {
        addr: string;
        balance: BigNumber;
        error: boolean;
      })[]
    >;

    "getBalances(address,address[])"(
      user: string,
      coins: string[],
      overrides?: CallOverrides
    ): Promise<
      ([string, BigNumber, boolean] & {
        addr: string;
        balance: BigNumber;
        error: boolean;
      })[]
    >;
  };

  filters: {};

  estimateGas: {
    USD(overrides?: CallOverrides): Promise<BigNumber>;

    "USD()"(overrides?: CallOverrides): Promise<BigNumber>;

    checkPrice(token: string, overrides?: CallOverrides): Promise<BigNumber>;

    "checkPrice(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBalancePrices(
      user: string,
      coins: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getBalancePrices(address,address[])"(
      user: string,
      coins: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBalances(
      user: string,
      coins: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getBalances(address,address[])"(
      user: string,
      coins: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    USD(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "USD()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    checkPrice(
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "checkPrice(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBalancePrices(
      user: string,
      coins: string[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getBalancePrices(address,address[])"(
      user: string,
      coins: string[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBalances(
      user: string,
      coins: string[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getBalances(address,address[])"(
      user: string,
      coins: string[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
