/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface CheckerInterface extends ethers.utils.Interface {
  functions: {
    "UniswapFactoryAddress()": FunctionFragment;
    "checkPrice(address,address)": FunctionFragment;
    "getBalancePrices(address,address[],address)": FunctionFragment;
    "getBalances(address,address[])": FunctionFragment;
    "manager()": FunctionFragment;
    "setUniswapFactory(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "UniswapFactoryAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "checkPrice",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getBalancePrices",
    values: [string, string[], string]
  ): string;
  encodeFunctionData(
    functionFragment: "getBalances",
    values: [string, string[]]
  ): string;
  encodeFunctionData(functionFragment: "manager", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setUniswapFactory",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "UniswapFactoryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "checkPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBalancePrices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "manager", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setUniswapFactory",
    data: BytesLike
  ): Result;

  events: {};
}

export class Checker extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: CheckerInterface;

  functions: {
    UniswapFactoryAddress(overrides?: CallOverrides): Promise<[string]>;

    "UniswapFactoryAddress()"(overrides?: CallOverrides): Promise<[string]>;

    checkPrice(
      base: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { price: BigNumber }>;

    "checkPrice(address,address)"(
      base: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { price: BigNumber }>;

    getBalancePrices(
      user: string,
      coins: string[],
      priceBase: string,
      overrides?: CallOverrides
    ): Promise<
      [
        ([string, BigNumber, BigNumber, boolean] & {
          addr: string;
          balance: BigNumber;
          price: BigNumber;
          error: boolean;
        })[]
      ]
    >;

    "getBalancePrices(address,address[],address)"(
      user: string,
      coins: string[],
      priceBase: string,
      overrides?: CallOverrides
    ): Promise<
      [
        ([string, BigNumber, BigNumber, boolean] & {
          addr: string;
          balance: BigNumber;
          price: BigNumber;
          error: boolean;
        })[]
      ]
    >;

    getBalances(
      user: string,
      coins: string[],
      overrides?: CallOverrides
    ): Promise<
      [
        ([string, BigNumber, boolean] & {
          addr: string;
          balance: BigNumber;
          error: boolean;
        })[]
      ]
    >;

    "getBalances(address,address[])"(
      user: string,
      coins: string[],
      overrides?: CallOverrides
    ): Promise<
      [
        ([string, BigNumber, boolean] & {
          addr: string;
          balance: BigNumber;
          error: boolean;
        })[]
      ]
    >;

    manager(overrides?: CallOverrides): Promise<[string]>;

    "manager()"(overrides?: CallOverrides): Promise<[string]>;

    setUniswapFactory(
      uniswapFactor: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setUniswapFactory(address)"(
      uniswapFactor: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  UniswapFactoryAddress(overrides?: CallOverrides): Promise<string>;

  "UniswapFactoryAddress()"(overrides?: CallOverrides): Promise<string>;

  checkPrice(
    base: string,
    token: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "checkPrice(address,address)"(
    base: string,
    token: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getBalancePrices(
    user: string,
    coins: string[],
    priceBase: string,
    overrides?: CallOverrides
  ): Promise<
    ([string, BigNumber, BigNumber, boolean] & {
      addr: string;
      balance: BigNumber;
      price: BigNumber;
      error: boolean;
    })[]
  >;

  "getBalancePrices(address,address[],address)"(
    user: string,
    coins: string[],
    priceBase: string,
    overrides?: CallOverrides
  ): Promise<
    ([string, BigNumber, BigNumber, boolean] & {
      addr: string;
      balance: BigNumber;
      price: BigNumber;
      error: boolean;
    })[]
  >;

  getBalances(
    user: string,
    coins: string[],
    overrides?: CallOverrides
  ): Promise<
    ([string, BigNumber, boolean] & {
      addr: string;
      balance: BigNumber;
      error: boolean;
    })[]
  >;

  "getBalances(address,address[])"(
    user: string,
    coins: string[],
    overrides?: CallOverrides
  ): Promise<
    ([string, BigNumber, boolean] & {
      addr: string;
      balance: BigNumber;
      error: boolean;
    })[]
  >;

  manager(overrides?: CallOverrides): Promise<string>;

  "manager()"(overrides?: CallOverrides): Promise<string>;

  setUniswapFactory(
    uniswapFactor: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setUniswapFactory(address)"(
    uniswapFactor: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    UniswapFactoryAddress(overrides?: CallOverrides): Promise<string>;

    "UniswapFactoryAddress()"(overrides?: CallOverrides): Promise<string>;

    checkPrice(
      base: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "checkPrice(address,address)"(
      base: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBalancePrices(
      user: string,
      coins: string[],
      priceBase: string,
      overrides?: CallOverrides
    ): Promise<
      ([string, BigNumber, BigNumber, boolean] & {
        addr: string;
        balance: BigNumber;
        price: BigNumber;
        error: boolean;
      })[]
    >;

    "getBalancePrices(address,address[],address)"(
      user: string,
      coins: string[],
      priceBase: string,
      overrides?: CallOverrides
    ): Promise<
      ([string, BigNumber, BigNumber, boolean] & {
        addr: string;
        balance: BigNumber;
        price: BigNumber;
        error: boolean;
      })[]
    >;

    getBalances(
      user: string,
      coins: string[],
      overrides?: CallOverrides
    ): Promise<
      ([string, BigNumber, boolean] & {
        addr: string;
        balance: BigNumber;
        error: boolean;
      })[]
    >;

    "getBalances(address,address[])"(
      user: string,
      coins: string[],
      overrides?: CallOverrides
    ): Promise<
      ([string, BigNumber, boolean] & {
        addr: string;
        balance: BigNumber;
        error: boolean;
      })[]
    >;

    manager(overrides?: CallOverrides): Promise<string>;

    "manager()"(overrides?: CallOverrides): Promise<string>;

    setUniswapFactory(
      uniswapFactor: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setUniswapFactory(address)"(
      uniswapFactor: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    UniswapFactoryAddress(overrides?: CallOverrides): Promise<BigNumber>;

    "UniswapFactoryAddress()"(overrides?: CallOverrides): Promise<BigNumber>;

    checkPrice(
      base: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "checkPrice(address,address)"(
      base: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBalancePrices(
      user: string,
      coins: string[],
      priceBase: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getBalancePrices(address,address[],address)"(
      user: string,
      coins: string[],
      priceBase: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBalances(
      user: string,
      coins: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getBalances(address,address[])"(
      user: string,
      coins: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    manager(overrides?: CallOverrides): Promise<BigNumber>;

    "manager()"(overrides?: CallOverrides): Promise<BigNumber>;

    setUniswapFactory(
      uniswapFactor: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setUniswapFactory(address)"(
      uniswapFactor: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    UniswapFactoryAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "UniswapFactoryAddress()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkPrice(
      base: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "checkPrice(address,address)"(
      base: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBalancePrices(
      user: string,
      coins: string[],
      priceBase: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getBalancePrices(address,address[],address)"(
      user: string,
      coins: string[],
      priceBase: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBalances(
      user: string,
      coins: string[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getBalances(address,address[])"(
      user: string,
      coins: string[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    manager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "manager()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setUniswapFactory(
      uniswapFactor: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setUniswapFactory(address)"(
      uniswapFactor: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
